#!/usr/bin/env python3
from pathlib import Path

M="<!--FINAL-->"
def e(f,c):
    t=f.read_text()
    if M in t:return False
    p=t.rfind('</article>')
    if p>0:f.write_text(t[:p]+'\n'+M+'\n'+c+'\n</article>'+t[p+10:]);return True
    return False

b=Path("src/pages/blog")
d={
"investir-voglans-2025.astro":'<div class="bg-gradient-to-r from-indigo-50 to-purple-50 rounded-xl p-8 my-12"><h2 class="text-3xl font-bold mb-6">🎯 Guide Complet Débutant</h2><div class="space-y-4"><div class="bg-white rounded-lg p-5 shadow-md"><div class="flex gap-4"><div class="w-10 h-10 bg-indigo-600 rounded-full flex items-center justify-center text-white font-bold">1</div><div><h3 class="font-bold text-lg">Budget & Financement</h3><p class="text-sm">Capacité emprunt = Revenus×33%×300. Ex: 3000€/mois → 190k€ sur 20 ans</p></div></div></div><div class="bg-white rounded-lg p-5 shadow-md"><div class="flex gap-4"><div class="w-10 h-10 bg-indigo-600 rounded-full flex items-center justify-center text-white font-bold">2</div><div><h3 class="font-bold text-lg">Sélection Bien</h3><p class="text-sm">Emplacement > État. Transports+commerces <10min = location facile</p></div></div></div></div></div><div class="bg-gradient-to-r from-emerald-50 to-teal-50 rounded-xl p-8 my-12"><h2 class="text-3xl font-bold mb-6">💰 Simulation T2 Voglans</h2><div class="bg-white rounded-lg p-6 shadow-md"><div class="grid md:grid-cols-2 gap-4 text-sm"><div><h4 class="font-bold mb-2">Investissement</h4><div class="space-y-1"><div class="flex justify-between"><span>Prix T2</span><strong>145k€</strong></div><div class="flex justify-between"><span>Frais</span><strong>11k€</strong></div><div class="flex justify-between"><span>Meubles</span><strong>6k€</strong></div><div class="flex justify-between bg-emerald-50 p-2 rounded"><span>TOTAL</span><strong>162k€</strong></div></div></div><div><h4 class="font-bold mb-2">Rentabilité</h4><div class="space-y-1"><div class="flex justify-between"><span>Loyer/mois</span><strong>680€</strong></div><div class="flex justify-between"><span>Loyers/an</span><strong>8160€</strong></div><div class="flex justify-between"><span>Charges</span><strong>-2285€</strong></div><div class="flex justify-between bg-green-50 p-2 rounded"><span>Net</span><strong class="text-green-700">5875€ (3,6%)</strong></div></div></div></div></div></div>',

"investir-voglans-savoie.astro":'<div class="bg-gradient-to-r from-cyan-50 to-blue-50 rounded-xl p-8 my-12"><h2 class="text-3xl font-bold mb-6">💼 Fiscalité LMNP 2025</h2><div class="grid md:grid-cols-2 gap-6"><div class="bg-white rounded-lg p-6 shadow-md"><h3 class="font-bold text-lg mb-3">Amortissement</h3><div class="p-3 bg-cyan-50 rounded text-sm"><p class="font-semibold">Bien 200k€ meublé</p><p>Amortissement 85% = 170k€/20ans</p><p class="text-cyan-700 font-bold">→ 8500€/an déductibles</p></div><div class="p-3 bg-green-50 rounded text-sm mt-3"><p class="font-semibold">Loyers 10k€/an</p><p>SANS LMNP : 3000€ impôts</p><p class="text-green-700 font-bold">AVEC LMNP : 0€ pendant 10-15 ans</p></div></div><div class="bg-white rounded-lg p-6 shadow-md"><h3 class="font-bold text-lg mb-3">Déficit Foncier</h3><div class="p-3 bg-blue-50 rounded text-sm"><p class="font-semibold">Travaux 25k€</p><p>Max 10700€/an déductibles</p><p class="text-blue-700 font-bold">Économie: 7500€ impôts</p></div></div></div></div>',

"marche-immobilier-voglans-2025.astro":'<div class="bg-gradient-to-r from-red-50 to-pink-50 rounded-xl p-8 my-12"><h2 class="text-3xl font-bold mb-6">⚡ Opportunités 2025</h2><div class="grid md:grid-cols-3 gap-4"><div class="bg-white rounded-lg p-5 shadow-md"><h3 class="font-bold mb-2">🏠 Biens Rénover</h3><p class="text-sm">Décote 15-20%. Potentiel +40k€ après 15k€ travaux</p><div class="text-xs mt-2 text-green-600 font-bold">ROI: 250%</div></div><div class="bg-white rounded-lg p-5 shadow-md"><h3 class="font-bold mb-2">🔑 Ventes Rapides</h3><p class="text-sm">Vendeurs pressés = négociation -10-15%</p><div class="text-xs mt-2 text-green-600 font-bold">Économie: 15-25k€</div></div><div class="bg-white rounded-lg p-5 shadow-md"><h3 class="font-bold mb-2">📍 Zones Émergentes</h3><p class="text-sm">Prix -20%. Valorisation +30% en 3-5 ans</p><div class="text-xs mt-2 text-green-600 font-bold">Potentiel: +35%</div></div></div></div>',

"quartiers-voglans-guide-complet.astro":'<div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-xl p-8 my-12"><h2 class="text-3xl font-bold mb-6">🏘️ Comparatif 5 Quartiers</h2><div class="overflow-x-auto"><table class="w-full bg-white rounded-lg shadow-lg text-sm"><thead class="bg-orange-600 text-white"><tr><th class="px-3 py-2 text-left">Quartier</th><th class="px-3 py-2">Prix/m²</th><th class="px-3 py-2">Profil</th><th class="px-3 py-2 text-center">Note</th></tr></thead><tbody><tr><td class="px-3 py-2 font-bold">Centre Village</td><td class="px-3 py-2">2800-3100€</td><td class="px-3 py-2">Familles</td><td class="px-3 py-2 text-center">⭐⭐⭐⭐⭐</td></tr><tr class="bg-gray-50"><td class="px-3 py-2 font-bold">Technopôle</td><td class="px-3 py-2">2600-2900€</td><td class="px-3 py-2">Investisseurs</td><td class="px-3 py-2 text-center">⭐⭐⭐⭐⭐</td></tr><tr><td class="px-3 py-2 font-bold">Proche Lac</td><td class="px-3 py-2">3000-3400€</td><td class="px-3 py-2">Aisés</td><td class="px-3 py-2 text-center">⭐⭐⭐⭐☆</td></tr><tr class="bg-gray-50"><td class="px-3 py-2 font-bold">Pavillonnaire</td><td class="px-3 py-2">2400-2700€</td><td class="px-3 py-2">Primo</td><td class="px-3 py-2 text-center">⭐⭐⭐⭐☆</td></tr></tbody></table></div></div><div class="bg-rose-50 rounded-xl p-8 my-12"><h2 class="text-3xl font-bold mb-6">🔮 Prévisions 2025-2030</h2><div class="bg-white rounded-lg p-5 shadow-md"><table class="w-full text-sm"><thead class="bg-rose-100"><tr><th class="px-3 py-2">Quartier</th><th class="px-3 py-2">2025</th><th class="px-3 py-2">2030</th></tr></thead><tbody><tr><td class="px-3 py-2 font-semibold">Centre</td><td class="px-3 py-2">3000€</td><td class="px-3 py-2 text-green-600">3450€ (+15%)</td></tr><tr class="bg-gray-50"><td class="px-3 py-2 font-semibold">Technopôle</td><td class="px-3 py-2">2850€</td><td class="px-3 py-2 text-green-600">3450€ (+21%)</td></tr><tr><td class="px-3 py-2 font-semibold">Périphérie</td><td class="px-3 py-2">2420€</td><td class="px-3 py-2 text-emerald-600 font-bold">3100€ (+28%)</td></tr></tbody></table></div></div>'
}

c=0
for fn,ct in d.items():
    fp=b/fn
    if fp.exists() and e(fp,ct):c+=1;print(f"✅ {fn}")
print(f"\n🎉 {c}/4 enrichis!")
